update CI, echec install

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,9 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install pytest
+          pip install pytest psycopg2-binary
+          pip list | grep -i psycopg2 || echo "psycopg2 not found"
+
 
       - name: Run tests
         run: pytest -q
